# Generated by Django 5.1.4 on 2026-09-12 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('iperc', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='inicio del periodo')),
                ('period_end', models.DateField(verbose_name='fin del periodo')),
                ('is_supervisor_mode', models.BooleanField(default=False, verbose_name='modo supervisor (empresa con menos de 20 trabajadores)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='accounts.company')),
            ],
            options={
                'verbose_name': 'comité de SST',
                'verbose_name_plural': 'comités de SST',
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('SECRETARIO', 'Secretario'), ('TITULAR', 'Miembro titular'), ('SUPLENTE', 'Miembro suplente'), ('SUPERVISOR', 'Supervisor de SST')], max_length=12, verbose_name='cargo')),
                ('represents', models.CharField(choices=[('EMPLEADOR', 'Representante del empleador'), ('TRABAJADORES', 'Representante de los trabajadores')], max_length=14, verbose_name='representa a')),
                ('is_active', models.BooleanField(default=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='committee.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'miembro del comité',
                'verbose_name_plural': 'miembros del comité',
                'ordering': ('role', 'user__last_name'),
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='número de acta')),
                ('date', models.DateField(verbose_name='fecha de la reunión')),
                ('place', models.CharField(blank=True, max_length=200, verbose_name='lugar')),
                ('is_extraordinary', models.BooleanField(default=False, verbose_name='extraordinaria')),
                ('agenda', models.TextField(blank=True, verbose_name='agenda')),
                ('minutes', models.TextField(blank=True, verbose_name='desarrollo del acta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings_attended', to='committee.committeemember')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='committee.committee')),
            ],
            options={
                'verbose_name': 'acta de reunión',
                'verbose_name_plural': 'actas de reunión',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='acuerdo')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='plazo')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('CUMPLIDO', 'Cumplido'), ('NO_CUMPLIDO', 'No cumplido')], default='PENDIENTE', max_length=12, verbose_name='estado')),
                ('related_iperc_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_agreements', to='iperc.ipercentry')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_agreements', to='reports.report')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_agreements', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='committee.meeting')),
            ],
            options={
                'verbose_name': 'acuerdo',
                'verbose_name_plural': 'acuerdos',
                'ordering': ('due_date',),
            },
        ),
        migrations.AddConstraint(
            model_name='committeemember',
            constraint=models.UniqueConstraint(fields=('committee', 'user'), name='unique_member_per_committee'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(fields=('committee', 'number'), name='unique_meeting_number_per_committee'),
        ),
    ]
