# Generated by Django 5.1.4 on 2026-10-07 22:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='datos de demostración'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_sharing',
            field=models.BooleanField(default=True, verbose_name='comparte su ubicación'),
        ),
        migrations.CreateModel(
            name='PrivacyConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_version', models.CharField(max_length=20, verbose_name='versión de la política')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='otorgado el')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revocado el')),
                ('source', models.CharField(choices=[('WEB', 'Panel web'), ('ANDROID', 'Aplicación Android')], default='WEB', max_length=10, verbose_name='origen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consentimiento de privacidad',
                'verbose_name_plural': 'consentimientos de privacidad',
                'ordering': ('-granted_at',),
            },
        ),
    ]
