# Generated by Django 5.1.4 on 2026-10-07 22:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='uuid del cliente')),
                ('kind', models.CharField(choices=[('ACCIDENTE', 'Accidente de trabajo'), ('INCIDENTE_PELIGROSO', 'Incidente peligroso')], max_length=20, verbose_name='tipo')),
                ('severity', models.CharField(choices=[('LEVE', 'Leve'), ('INCAPACITANTE', 'Incapacitante'), ('MORTAL', 'Mortal')], default='LEVE', max_length=15, verbose_name='gravedad')),
                ('status', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('EN_INVESTIGACION', 'En investigación'), ('CERRADO', 'Cerrado')], default='REGISTRADO', max_length=18, verbose_name='estado')),
                ('place', models.CharField(blank=True, max_length=200, verbose_name='lugar exacto')),
                ('description', models.TextField(verbose_name='descripción del hecho')),
                ('injury_description', models.TextField(blank=True, verbose_name='lesión o daño')),
                ('immediate_actions', models.TextField(blank=True, verbose_name='acciones inmediatas tomadas')),
                ('injured_name', models.CharField(blank=True, max_length=150, verbose_name='nombre del accidentado')),
                ('injured_dni', models.CharField(blank=True, max_length=8, verbose_name='DNI del accidentado')),
                ('lost_days', models.PositiveIntegerField(default=0, verbose_name='días perdidos')),
                ('mtpe_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='avisado al MTPE el')),
                ('mtpe_notice_code', models.CharField(blank=True, max_length=80, verbose_name='cargo o constancia del aviso')),
                ('occurred_at', models.DateTimeField(verbose_name='ocurrió el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='cerrado el')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents', to='accounts.area')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='accounts.company')),
                ('injured_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents_suffered', to=settings.AUTH_USER_MODEL, verbose_name='trabajador accidentado')),
                ('origin_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents', to='reports.report', verbose_name='hallazgo previo relacionado')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accidents_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'accidente',
                'verbose_name_plural': 'accidentes',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='CorrectiveMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='medida')),
                ('control_kind', models.CharField(choices=[('ELIMINACION', 'Eliminación del peligro'), ('SUSTITUCION', 'Sustitución'), ('INGENIERIA', 'Control de ingeniería'), ('ADMINISTRATIVO', 'Control administrativo o señalización'), ('EPP', 'Equipo de protección personal')], default='ADMINISTRATIVO', max_length=15, verbose_name='nivel de control')),
                ('due_date', models.DateField(verbose_name='plazo')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('IMPLEMENTADA', 'Implementada'), ('VERIFICADA', 'Verificada')], default='PENDIENTE', max_length=15, verbose_name='estado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='implementada el')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verificada el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='accidents.accident')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measures_responsible', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measures_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'medida correctiva',
                'verbose_name_plural': 'medidas correctivas',
                'ordering': ('due_date',),
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('ARBOL_DE_CAUSAS', 'Árbol de causas'), ('CINCO_POR_QUE', 'Cinco por qué'), ('ISHIKAWA', 'Diagrama de Ishikawa'), ('OTRA', 'Otra')], default='CINCO_POR_QUE', max_length=20, verbose_name='metodología')),
                ('immediate_causes', models.TextField(blank=True, verbose_name='causas inmediatas')),
                ('basic_causes', models.TextField(blank=True, verbose_name='causas básicas')),
                ('root_cause', models.TextField(verbose_name='causa raíz')),
                ('conclusions', models.TextField(blank=True, verbose_name='conclusiones')),
                ('participants', models.CharField(blank=True, max_length=255, verbose_name='participantes')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='investigado el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation', to='accidents.accident')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'investigación',
                'verbose_name_plural': 'investigaciones',
            },
        ),
        migrations.CreateModel(
            name='OccupationalDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(blank=True, max_length=150, verbose_name='nombre del trabajador')),
                ('diagnosis', models.CharField(max_length=200, verbose_name='diagnóstico')),
                ('cie10_code', models.CharField(blank=True, max_length=10, verbose_name='código CIE-10')),
                ('causal_agent', models.CharField(blank=True, max_length=150, verbose_name='agente causal')),
                ('exposure_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='meses de exposición')),
                ('diagnosed_on', models.DateField(verbose_name='diagnosticada el')),
                ('status', models.CharField(choices=[('SOSPECHA', 'Sospecha'), ('CONFIRMADA', 'Confirmada'), ('DESCARTADA', 'Descartada')], default='SOSPECHA', max_length=12, verbose_name='estado')),
                ('rest_days', models.PositiveIntegerField(default=0, verbose_name='días de descanso médico')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupational_diseases', to='accounts.area')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupational_diseases', to='accounts.company')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diseases_reported', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diseases', to=settings.AUTH_USER_MODEL, verbose_name='trabajador')),
            ],
            options={
                'verbose_name': 'enfermedad ocupacional',
                'verbose_name_plural': 'enfermedades ocupacionales',
                'ordering': ('-diagnosed_on',),
            },
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['company', 'status'], name='accidents_a_company_13869f_idx'),
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['company', '-occurred_at'], name='accidents_a_company_d7cea9_idx'),
        ),
    ]
