# Generated by Django 5.1.4 on 2026-09-12 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('checklist', models.JSONField(blank=True, default=list, verbose_name='checklist')),
                ('frequency', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral')], max_length=12, verbose_name='frecuencia')),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_schedules', to='accounts.area')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_schedules', to='accounts.company')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'programa de inspección',
                'verbose_name_plural': 'programas de inspección',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='fecha programada')),
                ('performed_at', models.DateTimeField(blank=True, null=True, verbose_name='realizada el')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REALIZADA', 'Realizada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=12, verbose_name='estado')),
                ('findings', models.TextField(blank=True, verbose_name='hallazgos')),
                ('results', models.JSONField(blank=True, default=dict, verbose_name='resultados del checklist')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inspections.inspectionschedule')),
            ],
            options={
                'verbose_name': 'inspección',
                'verbose_name_plural': 'inspecciones',
                'ordering': ('-due_date',),
            },
        ),
    ]
