# Generated by Django 5.1.4 on 2026-09-12 20:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EppItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('lifespan_days', models.PositiveIntegerField(default=180, verbose_name='vida útil (días)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epp_items', to='accounts.company')),
            ],
            options={
                'verbose_name': 'EPP',
                'verbose_name_plural': 'EPP',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EppDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='entregado el')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='vence el')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='conforme del trabajador')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='observaciones')),
                ('delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epp_handed_over', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epp_deliveries', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='epp.eppitem')),
            ],
            options={
                'verbose_name': 'entrega de EPP',
                'verbose_name_plural': 'entregas de EPP',
                'ordering': ('-delivered_at',),
            },
        ),
    ]
