# Generated by Django 5.1.4 on 2026-09-12 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IpercMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versión')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VIGENTE', 'Vigente'), ('HISTORICA', 'Histórica')], default='BORRADOR', max_length=12, verbose_name='estado')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='vigente desde')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iperc_matrices', to='accounts.company')),
            ],
            options={
                'verbose_name': 'matriz IPERC',
                'verbose_name_plural': 'matrices IPERC',
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='IpercEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=150, verbose_name='puesto / tarea')),
                ('hazard', models.CharField(max_length=255, verbose_name='peligro')),
                ('risk', models.CharField(max_length=255, verbose_name='riesgo')),
                ('probability', models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2, verbose_name='probabilidad')),
                ('consequence', models.PositiveSmallIntegerField(choices=[(1, 'Ligeramente dañino'), (2, 'Dañino'), (3, 'Extremadamente dañino')], default=2, verbose_name='consecuencia')),
                ('existing_controls', models.TextField(blank=True, verbose_name='controles existentes')),
                ('proposed_controls', models.TextField(blank=True, verbose_name='controles propuestos')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iperc_entries', to='accounts.area')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iperc_entries', to='reports.report')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='iperc.ipercmatrix')),
            ],
            options={
                'verbose_name': 'entrada IPERC',
                'verbose_name_plural': 'entradas IPERC',
                'ordering': ('area__name', 'job_position'),
            },
        ),
        migrations.AddConstraint(
            model_name='ipercmatrix',
            constraint=models.UniqueConstraint(fields=('company', 'version'), name='unique_iperc_version_per_company'),
        ),
    ]
