# Generated by Django 5.1.4 on 2026-09-12 20:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('kind', models.CharField(choices=[('ACTO', 'Acto inseguro (lo que hace la persona)'), ('CONDICION', 'Condición insegura (lo que hay en el ambiente)')], max_length=12, verbose_name='aplica a')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='icono')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.company')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='uuid del cliente')),
                ('kind', models.CharField(choices=[('ACTO', 'Acto inseguro (lo que hace la persona)'), ('CONDICION', 'Condición insegura (lo que hay en el ambiente)')], max_length=12, verbose_name='tipo')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('severity', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10, verbose_name='severidad')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='foto')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud')),
                ('status', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En proceso'), ('CERRADO', 'Cerrado'), ('DESCARTADO', 'Descartado')], default='ABIERTO', max_length=12, verbose_name='estado')),
                ('closure_note', models.TextField(blank=True, verbose_name='acción correctiva aplicada')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ocurrió el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='asignado el')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='cerrado el')),
                ('form_variant', models.CharField(blank=True, max_length=20, verbose_name='variante de formulario')),
                ('synced_offline', models.BooleanField(default=False, verbose_name='llegó por sincronización offline')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='accounts.area')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_assigned', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.company')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reporte',
                'verbose_name_plural': 'reportes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReportAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='comentario')),
                ('new_status', models.CharField(blank=True, choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En proceso'), ('CERRADO', 'Cerrado'), ('DESCARTADO', 'Descartado')], max_length=12, verbose_name='estado resultante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='reports.report')),
            ],
            options={
                'verbose_name': 'acción del reporte',
                'verbose_name_plural': 'acciones del reporte',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['company', 'status'], name='reports_rep_company_018554_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['company', '-created_at'], name='reports_rep_company_c5a865_idx'),
        ),
    ]
