# Generated by Django 5.1.4 on 2026-10-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='reporte anónimo'),
        ),
    ]
